version: 2
jobs:
  build:
    machine:
      image: android:202102-01
    steps:
    - checkout
    - run:
        command: |
          sdkmanager "system-images;android-29;default;x86"
        name: Install system image "system-images;android-29;default;x86"
    - run:
        command: |
          find . -name 'build.gradle' | sort | xargs cat |
          shasum | awk '{print $1}' > /tmp/gradle_cache_seed
        name: Generate cache checksum
    - restore_cache:
        key: gradle-v1a-{{ arch }}-{{ checksum "/tmp/gradle_cache_seed" }}
        name: Restore gradle cache
    - run:
        command: |
          ./gradlew build
        name: 'Run: ./gradlew build'
    - save_cache:
        key: gradle-v1a-{{ arch }}-{{ checksum "/tmp/gradle_cache_seed" }}
        name: Save gradle cache
        paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    - store_artifacts:
        path: algorigoutil/build/reports
        destination: reports
    - store_test_results:
        path: algorigoutil/build/test-results
    - persist_to_workspace:
        root: .
        paths:
          - .
    resource_class: medium
  deploy:
    machine:
      image: android:202102-01
    working_directory: ~/code
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Upload Bintray
          command: ./gradlew bintrayUpload -PbintrayUser=chagilhwan -PbintrayKey=$BINTRAY_API_KEY -PdryRun=false

workflows:
  version: 2
  build_deploy:
    jobs:
    - build
    - deploy:
        requires:
          - build
        filters:
          branches:
            only:
              - master
